In [63]:
import numpy as np
from numpy import arange
from numpy import vstack
from numpy import argmax
from numpy import asarray
from numpy.random import normal
from numpy.random import random
from scipy.stats import norm
from matplotlib import pyplot
from typing import Tuple, Union
from sklearn.gaussian_process import GaussianProcessRegressor

def objective(x, noise=0.1):
	noise = np.random.normal(loc=0, scale=noise)
	return (x**2 * np.sin(5 * np.pi * x)**6.0) + noise

# surrogate or approximation for the objective function
def surrogate(model, X):
    return model.predict(X, return_std=True)

# probability of improvement acquisition function
def acquisition(X, Xsamples, model):
	# calculate the best surrogate score found so far
	yhat, _ = surrogate(model, X)
    print(yhat)
	best = max(yhat)
	# calculate mean and stdev via surrogate function
	mu, std = surrogate(model, Xsamples)
    print(mu)
	mu = mu[:, 0]
	# calculate the probability of improvement
	probs = norm.cdf((mu - best) / (std+1e-9))
	return probs

# optimize the acquisition function
def opt_acquisition(X, y, model):
	# random search, generate random samples
	Xsamples = np.array([[i,j] for i,j in zip(random(100),random(100))])
	#Xsamples = Xsamples.reshape(len(Xsamples), 2)
	# calculate the acquisition function for each sample
	scores = acquisition(X, Xsamples, model)
	# locate the index of the largest scores
	ix = argmax(scores)
	return Xsamples[ix, 0]

# plot real observations vs surrogate function
def plot(X, y, model):
	# scatter plot of inputs and real objective function
	pyplot.scatter(X, y)
	# line plot of surrogate function across domain
	Xsamples = asarray(arange(0, 1, 0.001))
	Xsamples = Xsamples.reshape(len(Xsamples), 1)
	ysamples, _ = surrogate(model, Xsamples)
	pyplot.plot(Xsamples, ysamples)
	# show the plot
	pyplot.show()


IndentationError: unindent does not match any outer indentation level (<tokenize>, line 25)

In [31]:
Xsamples = random(100)
print(Xsamples)

[0.53285823 0.29938719 0.15767773 0.06772943 0.91695229 0.58732791
 0.91460201 0.86994    0.73047506 0.86101524 0.51679799 0.04480599
 0.47043897 0.43370559 0.97434054 0.52009418 0.12051314 0.5620684
 0.30027901 0.59212383 0.32676485 0.27991538 0.14510372 0.02299608
 0.67079794 0.26734324 0.379014   0.28787175 0.86892363 0.15732333
 0.98611624 0.46499406 0.51326592 0.81549373 0.28308395 0.82831073
 0.42754207 0.04512334 0.79215229 0.50386863 0.5848871  0.21048403
 0.51963858 0.1942338  0.74932734 0.4352872  0.86950652 0.65528279
 0.32027556 0.03415885 0.72735913 0.05113921 0.89892515 0.71998177
 0.81454949 0.69342998 0.07874588 0.09710418 0.99349633 0.54753295
 0.29147763 0.17145166 0.00224628 0.51763122 0.90193645 0.57531809
 0.71421868 0.04561599 0.40724401 0.39669655 0.60525349 0.39691681
 0.5733368  0.00376989 0.92681969 0.90594506 0.71113624 0.62685796
 0.08203213 0.69574792 0.8603258  0.29985832 0.58299691 0.17045403
 0.45269308 0.94448819 0.92590447 0.85601585 0.34460479 0.78420

In [12]:
def origin(x: np.array):
    return (x[0] - 1)**2 + (x[1] +2) **2 #max on (1,-2)
model = GaussianProcessRegressor()

In [13]:
X = np.linspace(-5, 5, 10) @
model.fit(x_init, origin(x_init))

SyntaxError: invalid syntax (<ipython-input-13-aa88173b65ac>, line 1)

In [20]:
x_init.reshape(len(x_init), 1)

array([[0],
       [0]])

In [112]:
def cartesian_product(*arrays):
    la = len(arrays)
    dtype = np.result_type(*arrays)
    arr = np.empty([len(a) for a in arrays] + [la], dtype=dtype)
    for i, a in enumerate(np.ix_(*arrays)):
        arr[...,i] = a
    return arr.reshape(-1, la)

In [170]:
t = np.linspace(-5, 5, 20)
X = cartesian_product(t,t)
Y = np.array([-origin(x) for x in X])

model.fit(X, Y)

GaussianProcessRegressor()

In [186]:
s = np.linspace(-6, 6, 200)
x_s = cartesian_product(s,s)
mu, std = model.predict(x_s, return_std = True)
print(max(mu))
print(std)

-0.00022633560001850128
[0.52732767 0.50233826 0.47963034 ... 0.47963035 0.50233827 0.52732767]


E:\Programs\Anaconda\lib\site-packages\sklearn\gaussian_process\_gpr.py:375: UserWarning: Predicted variances smaller than 0. Setting those variances to 0.
  warnings.warn("Predicted variances smaller than 0. "


In [187]:
best = max(Y)
print(best)
ix = argmax(norm.cdf((mu-best-1e-7)/std))
print(ix)
x_new = x_s[ix] #Следующий аргумент на проверку
y_new = -origin(x_new) 

x_new = x_new.reshape(1,2)
print(x_new)

X = np.append(X, x_new, axis = 0)
Y = np.append(Y, y_new) #После этого заново запускаем алгоритм
print(x_new, y_new)

-0.0543673139567184
22664
[[ 0.81407035 -2.14070352]]
[[ 0.81407035 -2.14070352]] -0.0543673139567184


<ipython-input-187-95a1aacf2097>:3: RuntimeWarning: divide by zero encountered in true_divide
  ix = argmax(norm.cdf((mu-best-1e-7)/std))


In [306]:
import numpy as np
from numpy import arange
from numpy import vstack
from numpy import argmax
from numpy import asarray
from numpy.random import uniform
from numpy.random import normal
from numpy.random import random
from scipy.stats import norm
import scipy.stats as sps
import matplotlib.pyplot as plt
from typing import Tuple, Union
from sklearn.gaussian_process import GaussianProcessRegressor


def cartesian_product(*arrays):
    la = len(arrays)
    dtype = np.result_type(*arrays)
    arr = np.empty([len(a) for a in arrays] + [la], dtype=dtype)
    for i, a in enumerate(np.ix_(*arrays)):
        arr[...,i] = a
    return arr.reshape(-1, la)

def sample():
    t = np.linspace(-20, 20, 400)
    Xs = cartesian_product(t,t,t,t,t,t,t,t,t,t) #нужно добавить 10 векторов
    return Xs

def acquisition(X, Y, model):
    
    X=X
    Y=Y
    model = model
    
    x_s = sample()
    mu, std = model.predict(x_s, return_std = True)
    
    best = max(Y)
    
    ix = argmax(norm.cdf(mu-best-1e-6/std))
    x_new = x_s[ix]
    x_new = x_new.reshape(1,10)
    return x_new

def get_y(origin): #Минус для минимизации
    return -origin(x_new)

def fit_new_model(X, Y):
    model = GaussianProcessRegressor()
    model.fit(X, Y)
    return model

In [262]:
def init(args_history):
    # Пример такой функции:
    if len(args_history) <= 1023:
        n = len(args_history)
        x_in = np.linspace(-10,10, 2)
        X = cartesian_product(x_in,x_in,x_in,x_in,x_in,x_in,x_in,x_in,x_in,x_in)
        print(X.shape)
        check = True
        return X[n], check
    else:
        check = False
        return args_history, check
    
    

def blackbox_optimize(
        args_history: np.ndarray,
        func_vals_history: np.ndarray
) -> Union[np.ndarray, str]:

    """
    Функция, которая по истории проверенных точек и значений blackbox функции в них возращает точку, которую следует
    проверить следующей или же строку "stop". Учтите случай, что должна выдавать функция, когда истории нет
    (args_history и func_vals_history это пустые arrays)

    Args:
        args_history: история аргументов (args_history.shape = (n, 10))
        func_vals_history: история значений функции в соответствующих аргументах
    Returns:
        Следующая точка (np.ndarray размера 10)
    """
    
    
    X, check = init(args_history)
    
    Y = func_vals_history
    if check == False:
        model = fit_new_model(X, Y)
        x_new = acquisition(X, Y, model)
    else:
        X = X.reshape(1,10)
        x_new = X
    
    return x_new

In [263]:
args_history = list()
func_vals_history = list()
for i in range(10000):
    print(i, end = '; ')
    x_new = blackbox_optimize(args_history, func_vals_history)
    x_new = x_new[0]
    y_new = origin(x_new)
    args_history.append(x_new)
    func_vals_history.append(y_new)
print(min(func_vals_history))

0; (1024, 10)
1; (1024, 10)
2; (1024, 10)
3; (1024, 10)
4; (1024, 10)
5; (1024, 10)
6; (1024, 10)
7; (1024, 10)
8; (1024, 10)
9; (1024, 10)
10; (1024, 10)
11; (1024, 10)
12; (1024, 10)
13; (1024, 10)
14; (1024, 10)
15; (1024, 10)
16; (1024, 10)
17; (1024, 10)
18; (1024, 10)
19; (1024, 10)
20; (1024, 10)
21; (1024, 10)
22; (1024, 10)
23; (1024, 10)
24; (1024, 10)
25; (1024, 10)
26; (1024, 10)
27; (1024, 10)
28; (1024, 10)
29; (1024, 10)
30; (1024, 10)
31; (1024, 10)
32; (1024, 10)
33; (1024, 10)
34; (1024, 10)
35; (1024, 10)
36; (1024, 10)
37; (1024, 10)
38; (1024, 10)
39; (1024, 10)
40; (1024, 10)
41; (1024, 10)
42; (1024, 10)
43; (1024, 10)
44; (1024, 10)
45; (1024, 10)
46; (1024, 10)
47; (1024, 10)
48; (1024, 10)
49; (1024, 10)
50; (1024, 10)
51; (1024, 10)
52; (1024, 10)
53; (1024, 10)
54; (1024, 10)
55; (1024, 10)
56; (1024, 10)
57; (1024, 10)
58; (1024, 10)
59; (1024, 10)
60; (1024, 10)
61; (1024, 10)
62; (1024, 10)
63; (1024, 10)
64; (1024, 10)
65; (1024, 10)
66; (1024, 10)
67; (

ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.

In [233]:
def origin(x: np.array):
    return (x[0] - 1)**2 + (x[1] +2) **2 + x[2] + x[3]+ x[4]+ x[5]+ x[6]+ x[7]+ x[8]+ x[9] #max on (1,-2)

In [265]:
np.linspace((-20,20), 10)

array([[-20.        ,  20.        ],
       [-19.3877551 ,  19.79591837],
       [-18.7755102 ,  19.59183673],
       [-18.16326531,  19.3877551 ],
       [-17.55102041,  19.18367347],
       [-16.93877551,  18.97959184],
       [-16.32653061,  18.7755102 ],
       [-15.71428571,  18.57142857],
       [-15.10204082,  18.36734694],
       [-14.48979592,  18.16326531],
       [-13.87755102,  17.95918367],
       [-13.26530612,  17.75510204],
       [-12.65306122,  17.55102041],
       [-12.04081633,  17.34693878],
       [-11.42857143,  17.14285714],
       [-10.81632653,  16.93877551],
       [-10.20408163,  16.73469388],
       [ -9.59183673,  16.53061224],
       [ -8.97959184,  16.32653061],
       [ -8.36734694,  16.12244898],
       [ -7.75510204,  15.91836735],
       [ -7.14285714,  15.71428571],
       [ -6.53061224,  15.51020408],
       [ -5.91836735,  15.30612245],
       [ -5.30612245,  15.10204082],
       [ -4.69387755,  14.89795918],
       [ -4.08163265,  14.69387755],
 

In [274]:
np.random.uniform(0, 10, 2)

array([6.63094366, 1.0666883 ])

In [280]:
np.arange(1,2,.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [294]:
un = sps.uniform(loc = [0,0], scale = [1,1])

In [319]:
x_min = np.array([-20]*10)
x_max = np.array([20]*10)

n = 40**3
size = [n, 10]
data = uniform(x_min, x_max, size)
print(data)
data.shape

[[ -7.34292859  11.15404125  -9.292822   ... -14.18856285   4.46528632
   -0.91734424]
 [ 12.75277411  -6.01108652  12.14295567 ...  -9.97751423 -18.61007822
   15.21580828]
 [ 15.09618038  14.82310119 -14.9521055  ...  11.50719065   3.40080787
   -7.51989041]
 ...
 [-19.75256754 -11.89188861  -9.82981783 ... -14.1267994    9.86749573
  -13.35635931]
 [ -1.10688715 -15.5163467    8.26111596 ...  15.04235471 -14.32648608
   13.64228885]
 [ 15.59322897   8.70936224  -6.69548984 ...   0.77869034  15.26077873
   13.99673944]]


(64000, 10)

In [312]:
np.array([10]*3)

array([10, 10, 10])